# Generated by Django 5.1.3 on 2024-11-14 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_alter_foodpost_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='firstname',
            field=models.CharField(default='null', max_length=255),
        ),
        migrations.AlterField(
            model_name='member',
            name='lastname',
            field=models.CharField(db_default='null', max_length=255),
        ),
    ]
